apiVersion: v1
kind: ConfigMap
metadata:
  name: narae-api
  namespace: narae-api
data:
  LOGIN_REDIRECT_URL: https://narae.narumir.io
  NAVER_CLIENT_ID: "D1sa9szPKoZZ87nZeCiP"
  KAKAO_CLIENT_ID: "d702fab7a1e36e8bc5959c1faac17b11"
  KAKAO_REDIRECT_URL: "https://api.05-project.narumir.io/api/v1/auth/kakao/callback"
  GOOGLE_CLIENT_ID: "44860597251-jscuuflrss4kk3noodu87pfe1qa8hbur.apps.googleusercontent.com"
  GOOGLE_REDIRECT_URL: "https://api.05-project.narumir.io/api/v1/auth/google/callback"
  AWS_CDN_URL: "https://cdn.narumir.io"
  AWS_S3_MEDIA_BUCKET: "narae_content"
